[package]
name = "bridge_server"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"

bridge_core = { path = "../bridge_core" }

[features]
default = []
direct_input = ["bridge_core/direct_input"]
